package com.wizer.signage.data.model

import kotlinx.serialization.Serializable

/**
 * One actual player playback event (Phase 9 proof-of-play). Generated by the
 * player's advancement loop — never inferred from heartbeat, sync status, or
 * manifest generation. The backend is the source of truth for tenancy; this
 * payload carries only what the device legitimately observed.
 */
@Serializable
data class ProofOfPlayEvent(
    val eventType: String, // ITEM_STARTED | ITEM_COMPLETED | ITEM_FAILED | ITEM_SKIPPED | ITEM_INTERRUPTED
    /** Idempotency key — unique per item playback. */
    val playbackSessionId: String,
    val startedAt: String,
    val endedAt: String? = null,
    val contentId: String? = null,
    val playlistId: String? = null,
    val playlistItemId: String? = null,
    val scheduleId: String? = null,
    val emergencyBroadcastId: String? = null,
    val sourceType: String? = null, // SCHEDULE | FALLBACK | EMERGENCY | NONE
    val playbackSource: String? = null, // LOCAL_CACHE | STREAMING_SIGNED_URL | TEXT | URL | PDF | UNKNOWN
    val contentType: String? = null, // IMAGE | VIDEO | PDF | URL | TEXT
    val durationMs: Long? = null,
    val expectedDurationMs: Long? = null,
    val itemSequence: Int? = null,
    val offlinePlayback: Boolean = false,
    val manifestVersion: String? = null,
    val failureReason: String? = null,
) {
    companion object {
        const val STARTED = "ITEM_STARTED"
        const val COMPLETED = "ITEM_COMPLETED"
        const val FAILED = "ITEM_FAILED"
        const val SKIPPED = "ITEM_SKIPPED"
        const val INTERRUPTED = "ITEM_INTERRUPTED"

        const val SOURCE_LOCAL_CACHE = "LOCAL_CACHE"
        const val SOURCE_STREAMING = "STREAMING_SIGNED_URL"
        const val SOURCE_TEXT = "TEXT"
        const val SOURCE_URL = "URL"
        const val SOURCE_UNKNOWN = "UNKNOWN"
    }
}

/** Device → backend batch (one online push or a flushed offline buffer). */
@Serializable
data class ReportProofOfPlayRequest(val events: List<ProofOfPlayEvent>)
